version: 2
jobs:
  test:
    working_directory: ~/work
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ~/key.json
      - run:
          name: Init terraform
          command: |
            terraform init ~/work/terraform
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
      - run:
          name: Validate terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform validate ~/work/terraform
      - run:
          name: Plan terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform plan ~/work/terraform
  deploy:
    working_directory: ~/work
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ~/key.json
      - run:
          name: Init terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform init ~/work/terraform
      - run:
          name: Apply terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform apply -auto-approve ~/work/terraform
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
