version: 2
jobs:
  terraform-test:
    working_directory: ~/work
    docker:
      - image: hashicorp/terraform:latest
    environment:
      TF_VAR_openapi_path: ~/work/terraform/endpoint/openapi_spec.yml
    steps:
      - checkout
      - run:
          name: create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ~/key.json
      - run:
          name: Init terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform init ~/work/terraform
      - run:
          name: Validate terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform validate ~/work/terraform
      - run:
          name: Plan terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform plan ~/work/terraform
  docker-test:
    working_directory: ~/work
    machine: true
    steps:
      - checkout
      - run:
          name: checking docker build 
          command: docker build ~/work/docker/flask_get_app
  docker-push:
    working_directory: ~/work
    docker:
      - image: google/cloud-sdk:latest
    environment:
      PROJECT: teraform-244604
      IMG_NAME: get-hello
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: gcloud auth
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ~/key.json
            gcloud auth activate-service-account --key-file ~/key.json
            gcloud --quiet auth configure-docker
      - run:
          name: docker build and push
          command: |
            DOCKER_BASE=asia.gcr.io/${PROJECT}/${IMG_NAME}
            if [ -z "${CIRCLE_BUILD_NUM}" ]; then
              CIRCLE_BUILD_NUM=1
            fi
            docker build -t ${DOCKER_BASE}:${CIRCLE_BUILD_NUM} ~/work/docker/flask_get_app
            docker tag ${DOCKER_BASE}:${CIRCLE_BUILD_NUM} ${DOCKER_BASE}:latest
            if [ -n "${CIRCLE_TAG}" ];then
              docker tag ${DOCKER_BASE}:${CIRCLE_BUILD_NUM} ${DOCKER_BASE}:${CIRCLE_TAG}
            fi
            docker push ${DOCKER_BASE}
  deploy:
    working_directory: ~/work
    docker:
      - image: hashicorp/terraform:light
    environment:
      TF_VAR_openapi_path: ~/work/terraform/endpoint/openapi_spec.yml
    steps:
      - checkout
      - run:
          name: create gcp credential
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > ~/key.json
      - run:
          name: Init terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform init ~/work/terraform
      - run:
          name: Apply terraform
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
            terraform apply -auto-approve ~/work/terraform
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - terraform-test
      - docker-test
      - docker-push:
          requires:
            - terraform-test
            - docker-test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - docker-push
          filters:
            branches:
              only: master
